CREATE DATABASE cajerosdb;

USE cajerosdb;
CREATE TABLE cajeros (
    Ncajero INT AUTO_INCREMENT PRIMARY KEY,
    N_de_Cajero INT,
    Departamento VARCHAR(255),
    Municipio VARCHAR(255),
    Lugar VARCHAR(255)
);

USE cajerosdb;

-- Inserta los datos en la tabla "cajeros"
INSERT INTO cajeros (N_de_Cajero, Departamento, Municipio, Lugar) VALUES
    (1, 'LA LIBERTAD', 'ANTIGUO CUSCATLÁN', 'Hospital Veterinario Chivopets'),
    (2, 'SAN SALVADOR', 'SAN SALVADOR', 'Megacentro Megacentro de Vacunación'),
    (3, 'SAN SALVADOR', 'SAN SALVADOR', 'B. Hipotecario Agencia Autopista Sur'),
    (4, 'LA LIBERTAD', 'COLÓN', 'Centros Comerciales El Encuentro Lourdes'),
    (1078, 'SAN SALVADOR', 'MEJICANOS', 'B. Hipotecario Agencia Zacamil'),
    (6, 'LA LIBERTAD', 'LA LIBERTAD', 'Mercados Municipales Mercado del Mar'),
    (7, 'LA LIBERTAD', 'COLÓN', 'B. Hipotecario Mini Agencia Lourdes'),
    (8, 'SAN SALVADOR', 'SAN SALVADOR', 'B. Hipotecario Senda Florida'),
    (9, 'SAN SALVADOR', 'SAN SALVADOR', 'B. Hipotecario Agencia Paseo Escalon'),
    (1027, 'SAN SALVADOR', 'SAN SALVADOR', 'B. Hipotecario Agencia 25 Av. Nte.'),
    (11, 'SAN SALVADOR', 'ILOPANGO', 'Centros Comerciales Unicentro Altavista'),
    (12, 'SONSONATE', 'SONSONATE', 'B. Hipotecario Agencia Sonsonate'),
    (13, 'LA LIBERTAD', 'SANTA TECLA', 'B. Hipotecario Agencia Merliot'),
    (14, 'LA LIBERTAD', 'LA LIBERTAD', 'B. Hipotecario Agencia Puerto De La Libertad'),
    (15, 'SAN SALVADOR', 'SAN SALVADOR', 'B. Hipotecario Agencia Centro San Salvador'),
    (16, 'LA LIBERTAD', 'SANTA TECLA', 'Centro Comercial Santa Rosa'),
    (18, 'LA LIBERTAD', 'SANTA TECLA', 'Punto Chivo Parque Daniel Hernández Santa Tecla'),
    (19, 'SAN SALVADOR', 'SAN SALVADOR', 'Punto Chivo Parque Cuscatlán Museo Tín Marín'),
    (20, 'SAN SALVADOR', 'SAN SALVADOR', 'Punto Chivo Plaza San Jacinto San Salvador'),
    (21, 'SAN SALVADOR', 'SAN SALVADOR', 'Mercados Municipales Ex Cuartel'),
    (10, 'SAN MIGUEL', 'SAN MIGUEL', 'Punto Chivo Sede INJUVE Centro San Miguel'),
    (24, 'SAN SALVADOR', 'APOPA', 'Correos Apopa'),
	(25, 'LA PAZ', 'SAN LUIS TALPA', 'Aeropuerto (2) Salas de Embarque Puerta 8'),
    (26, 'SAN SALVADOR', 'MEJICANOS', 'Centro Comercial Unicentro Metropolis'),
    (27, 'SAN SALVADOR', 'EL ZONTE', 'Turísticos Hope House Bitcoin Beach'),
    (28, 'LA LIBERTAD', 'ANTIGUO CUSCATLÁN', 'Centro Comercial Las Cascadas'),
    (29, 'SAN SALVADOR', 'APOPA', 'Lotería Agencia Apopa'),
    (30, 'LA LIBERTAD', 'SANTA TECLA', 'Centro Comercial Las Palmas'),
    (31, 'LA LIBERTAD', 'CIUDAD ARCE', 'Correos Ciudad Arce'),
    (32, 'SAN SALVADOR', 'SAN SALVADOR', 'Centro Comercial Bambu City Center'),
    (33, 'CUSCATLAN', 'COJUTEPEQUE', 'Correos Cojutepeque'),
    (34, 'LA PAZ', 'SAN LUIS TALPA', 'Aeropuerto (1) Salas Embarque Puerta 5'),
    (35, 'LA LIBERTAD', 'COLÓN', 'Centros Comerciales Metrocentro Lourdes'),
    (36, 'SANTA ANA', 'TEXISTEPEQUE', 'Correos Texistepeque'),
    (37, 'LA LIBERTAD', 'COLÓN', 'Correos Colon'),
    (38, 'SAN SALVADOR', 'SAN SALVADOR', 'Correos C.C. Metrocentro'),
    (39, 'CHALATENANGO', 'TEJUTLA', 'Correos El Coyolito'),
    (40, 'LA LIBERTAD', 'ANTIGUO CUSCATLÁN', 'Punto Chivo Parqueo Municipal Antiguo Cuscatlán'),
    (41, 'LA LIBERTAD', 'SANTA TECLA', 'Correos Santa Tecla'),
    (42, 'LA LIBERTAD', 'ANTIGUO CUSCATLÁN', 'Centros Comerciales Multiplaza'),
    (43, 'LA LIBERTAD', 'SANTA TECLA', 'Mercado Dueñas Santa Tecla'),
    (44, 'LA LIBERTAD', 'SANTA TECLA', 'Mercado Municipal de Santa Tecla'),
    (45, 'SAN SALVADOR', 'SAN MARTÍN', 'BFA Agencia San Martín'),
    (46, 'SAN SALVADOR', 'CIUDAD DELGADO', 'Punto Chivo Plaza techada Monseñor Romero Ciudad Delgado'),
    (47, 'SAN SALVADOR', 'SOYAPANGO', 'Punto Chivo CC Unicentro Soyapango'),
    (48, 'SAN SALVADOR', 'SAN MARTÍN', 'Punto Chivo Parque Central San Martín'),
    (49, 'LA LIBERTAD', 'SANTA TECLA', 'Punto Chivo C.C. Plaza Merliot Santa Tecla'),
    (50, 'LA LIBERTAD', 'ANTIGUO CUSCATLÁN', 'Punto Chivo Multiplaza Antiguo Cuscatlán'),
    (51, 'SAN SALVADOR', 'SAN SALVADOR', 'Punto Chivo CC El Paseo San Salvador'),
    (52, 'SAN SALVADOR', 'MEJICANOS', 'Punto Chivo Centro Comercial Unicentro Metrópolis Mejicanos'),
    (53, 'LA LIBERTAD', 'CIUDAD ARCE', 'Punto Chivo Parque Central Ciudad Arce'),
    (54, 'CUSCATLÁN', 'COJUTEPEQUE', 'Punto Chivo Parque Central Cojutepeque'),
    (55, 'AHUACHAPÁN', 'AHUACHAPÁN', 'Punto Chivo Mercado Municipal Ahuachapán'),
    (56, 'SAN SALVADOR', 'TONACATEPEQUE', 'Punto Chivo Parque Central Tonacatepeque'),
    (57, 'LA LIBERTAD', 'LOURDES', 'Centros Comerciales Centro Comercial Pasatiempo'),
    (58, 'SONSONATE', 'IZALCO', 'Punto Chivo Parque Central Izalco'),
    (59, 'LA LIBERTAD', 'SAN JUAN OPICO', 'Punto Chivo Parque Central San Juan Opico'),
    (60, 'SAN SALVADOR', 'SAN MARCOS', 'Centro Comercial El Encuentro San Marcos'),
    (61, 'SAN SALVADOR', 'ILOPANGO', 'Punto Chivo Centro Comercial Unicentro Altavista Ilopango'),
    (62, 'LA LIBERTAD', 'CIUDAD VERSALLES', 'Punto Chivo Ciudadela Ciudad Versalles'),
    (63, 'LA UNIÓN', 'LA UNIÓN', 'Punto Chivo Parque Central La Unión'),
    (64, 'CHALATENANGO', 'CHALATENANGO', 'Punto Chivo Parque Central Chalatenango'),
    (65, 'SANTA ANA', 'SANTA ANA', 'Punto Chivo Parque Colón Santa Ana'),
    (66, 'LA LIBERTAD', 'COLÓN', 'Punto Chivo Polideportivo de Lourdes Colón'),
    (67, 'SAN MIGUEL', 'SAN MIGUEL', 'Punto Chivo Centro de Gobierno Municipal San Miguel'),
    (68, 'SANTA ANA', 'METAPÁN', 'Punto Chivo Parque Municipal Metapán Metapán'),
    (69, 'SAN SALVADOR', 'APOPA', 'Punto Chivo Parque Central Apopa'),
	(70, 'AHUACHAPÁN', 'AHUACHAPÁN', 'Punto Chivo Parque Central Ahuachapán'),
    (71, 'SANTA ANA', 'SANTA ANA', 'Punto Chivo Alcaldía Santa Ana Santa Ana'),
    (72, 'SAN SALVADOR', 'SAN SALVADOR', 'Punto Chivo Centro Comercial Metrocentro San Salvador'),
    (73, 'SAN SALVADOR', 'SAN SALVADOR', 'Punto Chivo Salvador del Mundo San Salvador'),
    (74, 'SAN VICENTE', 'SAN VICENTE', 'Punto Chivo Parqueo Gobernación San Vicente'),
    (75, 'SAN MIGUEL', 'SAN MIGUEL', 'Punto Chivo Parqueo Mercado Municipal Ciudad Barrios'),
    (76, 'LA LIBERTAD', 'QUEZALTEPEQUE', 'Punto Chivo Parque Central Quezaltepeque'),
    (77, 'SAN SALVADOR', 'SOYAPANGO', 'Punto Chivo Centro Comercial Plaza Mundo Soyapango'),
    (78, 'CHALATENANGO', 'NUEVA CONCEPCIÓN', 'Correos Nueva Concepcion'),
    (79, 'SANTA ANA', 'CHALCHUAPA', 'Punto Chivo Parque José Matías Delgado Chalchuapa'),
    (80, 'LA UNION', 'SANTA ROSA DE LIMA', 'B. Hipotecario Agencia Santa Rosa de Lima'),
    (81, 'CHALATENANGO', 'LA PALMA', 'Turísticos Centro de Formación Municipal'),
    (82, 'CHALATENANGO', 'NUEVA CONCEPCIÓN', 'BFA Agencia Nueva Concepción'),
    (83, 'USULUTAN', 'BERLIN', 'B. Hipotecario Berlin'),
    (84, 'CHALATENANGO', 'NUEVA CONCEPCIÓN', 'B. Hipotecario Agencia Nueva Concepcion Chalatenango'),
    (85, 'SAN SALVADOR', 'MEJICANOS', 'Punto Chivo Alcaldía (Parqueo) Mejicanos'),
    (86, 'MORAZÁN', 'SAN FCO GOTERA', 'BFA Agencia San Francisco Gotera'),
    (87, 'CHALATENANGO', 'AGUA CALIENTE', 'Correos Agua Caliente'),
    (88, 'SAN SALVADOR', 'SAN SALVADOR', 'Punto Chivo Centro Comercial Metrosur San Salvador'),
    (89, 'SAN SALVADOR', 'APOPA', 'Punto Chivo CC Plaza Mundo Apopa'),
    (90, 'LA LIBERTAD', 'SANTA TECLA', 'Banco Cuscatlán Agencia Ciudad Merliot'),
    (91, 'SONSONATE', 'NAHUIZALCO', 'Punto Chivo Parque Central Nahuizalco'),
    (92, 'SAN SALVADOR', 'AGUILARES', 'Correos Aguilares'),
	(93, 'SANTA ANA', 'SANTA ANA', 'Punto Chivo CC Metrocentro Santa Ana'),
	(94, 'SONSONATE', 'ACAJUTLA', 'Punto Chivo Parque Interno Alcaldía Acajutla'),
	(95, 'LA LIBERTAD', 'LA LIBERTAD', 'Punto Chivo Parque Central La Libertad (Parque Centroamérica)'),
	(96, 'CABAÑAS', 'ILOBASCO', 'Punto Chivo Parque Central Ilobasco'),
	(97, 'MORAZÁN', 'SAN FRANCISCO GOTERA', 'Punto Chivo Parque Central San Francisco Gotera'),
	(108, 'LA PAZ', 'ZACATECOLUCA', 'Punto Chivo Plaza Cívica Zacatecoluca'),
	(111, 'SAN SALVADOR', 'AGUILARES', 'Punto Chivo Parque Aguilares Aguilares'),
	(112, 'SAN SALVADOR', 'GUAZAPA', 'Correos Guazapa'),
	(114, 'SONSONATE', 'SONSONATE', 'Punto Chivo Parque Rafael Campos Sonsonate'),
	(115, 'SAN SALVADOR', 'SOYAPANGO', 'CC Plaza Mundo Soyapango (cajero externo)'),
	(116, 'USULUTÁN', 'USULUTÁN', 'Punto Chivo Parque Central Usulután'),
	(117, 'CHALATENANGO', 'LA REINA', 'Correos La Reina'),
	(118, 'SAN SALVADOR', 'SOYAPANGO', 'Punto Chivo Plaza Jerusalén (Casa de la cultura) Soyapango'),
	(119, 'SAN SALVADOR', 'SAN SALVADOR', 'Punto Chivo Plaza Barrios San Salvador'),
	(120, 'SAN SALVADOR', 'SAN SALVADOR', 'Punto Chivo Plaza Morazán'),
	(1001, 'SANTA ANA', 'SANTA ANA', 'Banco Cuscatlán Avenida Independencia Sur, Santa Ana By Pass (Santa Ana)'),
	(1002, 'SANTA ANA', 'SANTA ANA', 'B. Hipotecario Agencia Santa Ana Los Heroes'),
	(1003, 'SANTA ANA', 'SANTA ANA', 'Centro Comercial La Zarzamora'),
	(1004, 'SANTA ANA', 'SANTA ANA', 'Lotería Agencia Regional Santa Ana'),
	(1005, 'SAN MIGUEL', 'SAN MIGUEL', 'B. Hipotecario Agencia San Miguel Centro'),
	(1007, 'SANTA ANA', 'SANTA ANA', 'B. Hipotecario Agencia Santa Ana Centro'),
	(1009, 'SANTA ANA', 'SAN SEBASTIÁN', 'BFA Agencia Santa Ana'),
	(1010, 'AHUACHAPÁN', 'AHUACHAPÁN', 'B. Hipotecario Agencia Ahuachapan'),
	(1011, 'AHUACHAPÁN', 'AHUACHAPÁN', 'Correos Ahuachapan'),
	(1012, 'AHUACHAPÁN', 'AHUACHAPÁN', 'DUICENTRO Ahuachapan'),
	(1013, 'SAN MIGUEL', 'SAN MIGUEL', 'Banco Cuscatlán San Miguel Roosevelt (San Miguel)'),
	(1014, 'SAN SALVADOR', 'SAN SALVADOR', 'Correos Plaza España'),
	(1015, 'LA LIBERTAD', 'SANTA TECLA', 'B. Hipotecario Agencia Santa Elena'),
	(1016, 'USULUTÁN', 'BERLIN', 'B. Hipotecario Geo Berlin (CEL)'),
	(1017, 'AHUACHAPÁN', 'SAN FRANCISCO MENÉNDEZ', 'Correos Cara Sucia'),
	(1018, 'SONSONATE', 'ACAJUTLA', 'Correos Acajutla'),
	(1019, 'AHUACHAPÁN', 'SAN FCO MENENDEZ', 'B. Hipotecario Agencia Cara Sucia'),
	(1020, 'SONSONATE', 'SONSONATE', 'Mercados Municipales Mercado de Sonsonate (Mega Plaza)'),
	(1021, 'SONSONATE', 'SONSONATE', 'DUICENTRO Sonsonate'),
	(1022, 'SONSONATE', 'SONSONATE', 'Banco Cuscatlán Sonsonate Las Palmeras (Sonsonate)'),
	(1023, 'SONSONATE', 'ARMENIA', 'Correos Armenia'),
	(1024, 'SANTA ANA', 'CANDELARIA DE LA FRONTERA', 'Correos Candelaria de la Frontera'),
	(1025, 'SONSONATE', 'IZALCO', 'Correos Izalco'),
	(1026, 'SANTA ANA', 'CHALCHUAPA', 'B. Hipotecario Agencia Chalchuapa'),
	(1027, 'SAN SALVADOR', 'SAN SALVADOR', 'B. Hipotecario Agencia 25 Av. Nte.'),
	(1028, 'LA PAZ', 'SAN LUIS TALPA', 'B. Hipotecario Agencia Aeropuerto'),
	(1029, 'LA PAZ', 'SANTIAGO NONUALCO', 'Correos Santiago Nonualco'),
	(1030, 'LA PAZ', 'ZACATECOLUCA', 'B. Hipotecario Agencia Zacatecoluca'),
	(1031, 'MORAZAN', 'CORINTO', 'Correos Morazan'),
	(1032, 'SAN SALVADOR', 'ILOPANGO', 'Alcaldía Alcaldía de Ilopango'),
	(1033, 'LA UNION', 'SANTA ROSA DE LIMA', 'Correos Santa Rosa de Lima'),
	(1034, 'SAN VICENTE', 'SAN VICENTE', 'B. Hipotecario Agencia San Vicente'),
	(1035, 'USULUTAN', 'JIQUILISCO', 'Correos de El Salvador, Jiquilisco'),
	(1036, 'USULUTÁN', 'USULUTÁN', 'B. Hipotecario Agencia Usulutan'),
	(1037, 'SAN MIGUEL', 'CHIRILAGUA', 'Hotel Marbella (Playa El Cuco)'),
	(1038, 'LA LIBERTAD', 'ANTIGUO CUSCATLÁN', 'Mercados Municipales Mercado de Merliot'),
	(1039, 'SAN SALVADOR', 'SAN SALVADOR', 'Casco Histórico Café Catedral'),
	(1040, 'SAN SALVADOR', 'SAN SALVADOR', 'Mercado Central de San Salvador'),
	(1041, 'AHUACHAPÁN', 'AHUACHAPÁN', 'BFA Agencia Ahuachapán'),
	(1042, 'SAN SALVADOR', 'SAN SALVADOR', 'Correos Centro de Gobierno'),
	(1043, 'SAN SALVADOR', 'SAN SALVADOR', 'Banco Cuscatlán Los Próceres (San Salvador)'),
	(1044, 'SAN SALVADOR', 'SAN SALVADOR', 'Banco Cuscatlán Caribe (San Salvador)'),
	(1045, 'SAN SALVADOR', 'SAN SALVADOR', 'Lotería Agencia Roosevelt'),
	(1046, 'MORAZÁN', 'SAN FCO GOTERA', 'B. Hipotecario Agencia San Francisco Gotera'),
	(1047, 'SAN SALVADOR', 'SAN SALVADOR', 'Gasolinera Gasolinera UNO La Garita'),
	(1048, 'SAN SALVADOR', 'SOYAPANGO', 'Centro Comercial Paseo Venecia'),
	(1050, 'SAN MIGUEL', 'SAN MIGUEL', 'B. Hipotecario Agencia San Miguel Roosevelt'),
	(1051, 'SAN MIGUEL', 'SAN MIGUEL', 'Alcaldía de San Miguel'),
	(1052, 'SAN SALVADOR', 'SAN SALVADOR', 'Banco Cuscatlán Cuscatlan (San Salvador)'),
	(1053, 'LA UNIÓN', 'LA UNIÓN', 'BFA Agencia La Unión'),
	(1054, 'SAN SALVADOR', 'SAN SALVADOR', 'Lotería Agencia Regional San Salvador'),
	(1055, 'MORAZAN', 'SAN FRANCISCO GOTERA', 'Correos San Francisco Gotera'),
	(1056, 'SANTA ANA', 'SAN SEBASTIÁN SALITRILLO', 'Centro Comercial MALL Plaza Real'),
	(1058, 'LA UNIÓN', 'ANAMORÓS', 'Correos Anamorós'),
	(1059, 'LA LIBERTAD', 'ANTIGUO CUSCATLÁN', 'Correos C.C. Plaza Merliot Santa Tecla'),
	(1060, 'SAN MIGUEL', 'SAN MIGUEL', 'BFA Agencia San Miguel'),
	(1061, 'SAN MIGUEL', 'SAN MIGUEL', 'Centros Comerciales CC El Encuentro Roosevelt, San Miguel'),
	(1063, 'USULUTAN', 'USULUTÁN', 'DUICENTRO Usulután'),
	(1064, 'SAN MIGUEL', 'CIUDAD BARRIOS', 'BFA Agencia Ciudad Barrios'),
	(1065, 'SAN MIGUEL', 'CIUDAD BARRIOS', 'Correos Ciudad Barrios'),
	(1066, 'SAN MIGUEL', 'CIUDAD BARRIOS', 'B. Hipotecario Agencia Ciudad Barrios'),
	(1067, 'LA LIBERTAD', 'SANTA TECLA', 'BFA Agencia Merliot'),
	(1068, 'CABAÑAS', 'ILOBASCO', 'Correos Ilobasco'),
	(1069, 'SAN SALVADOR', 'SAN SALVADOR', 'Mercado Municipal San Antonio'),
	(1071, 'CHALATENANGO', 'LA PALMA', 'Correos La Palma'),
	(1072, 'SANTA ANA', 'METAPÁN', 'Correos Metapan'),
	(1075, 'SAN SALVADOR', 'SAN SALVADOR', 'DUICENTRO Centro Comercial Galerías'),
	(1076, 'SONSONATE', 'SONSONATE', 'BFA Agencia Sonsonate'),
	(1077, 'SAN SALVADOR', 'SOYAPANGO', 'B. Hipotecario Mini Agencia Unicentro Soyapango'),
	(1078, 'SAN SALVADOR', 'MEJICANOS', 'B. Hipotecario Agencia Zacamil'),
	(1079, 'SANTA ANA', 'METAPÁN', 'BFA Agencia Metapán'),
	(1080, 'CUSCATLAN', 'SAN BARTOLOME PERULAPÍA', 'Correos San Bartolome Perulapia'),
	(1081, 'USULUTAN', 'SANTIAGO DE MARÍA', 'Correos Santiago de María'),
	(1082, 'CUSCATLAN', 'SUCHITOTO', 'Correos Suchitoto'),
	(1083, 'SAN SALVADOR', 'SAN SALVADOR', 'Alcaldía Alcaldía San Salvador'),
	(1084, 'CHALATENANGO', 'CHALATENANGO', 'Correos Chalatenango'),
	(1085, 'CUSCATLAN', 'SUCHITOTO', 'Mercados Municipales Mercado Municipal de Suchitoto'),
	(1086, 'CUSCATLÁN', 'COJUTEPEQUE', 'Lotería Mini agencia Cojutepeque'),
	(1087, 'SANTA ANA', 'SANTA ANA', 'B. Hipotecario Tudo Santa Ana'),
	(1088, 'SANTA ANA', 'METAPÁN', 'B. Hipotecario Agencia Metapan'),
	(1089, 'SAN SALVADOR', 'SAN MARTÍN', 'Centro Comercial El Encuentro San Martin'),
	(1090, 'LA LIBERTAD', 'SANTA TECLA', 'B. Hipotecario Agencia Santa Tecla'),
	(1091, 'USULUTAN', 'PUERTO EL TRIUNFO', 'Turísticos Capitania General'),
	(1092, 'USULUTÁN', 'JUCUAPA', 'BFA Agencia Jucuapa'),
	(1093, 'SAN MIGUEL', 'NUEVA GUADALUPE', 'Correos Nueva Guadalupe'),
	(1094, 'SAN VICENTE', 'SAN VICENTE', 'Correos San Vicente'),
	(1095, 'CABAÑAS', 'SENSUNTEPEQUE', 'Turísticos Parque Central Sensuntepeque'),
	(1096, 'CABAÑAS', 'SENSUNTEPEQUE', 'Correos Sensuntepeque'),
	(1097, 'USULUTÁN', 'USULUTÁN', 'BFA Agencia Usulután'),
	(1098, 'LA LIBERTAD', 'SANTA TECLA', 'Correos C.C. Plaza Merliot Santa Tecla'),
	(1099, 'CHALATENANGO', 'TEJUTLA', 'B. Hipotecario Mini Agencia El Coyolito'),
	(1100, 'SAN MIGUEL', 'SAN MIGUEL', 'Correos San Miguel'),
	(1102, 'SAN MIGUEL', 'SAN MIGUEL', 'Centros Comerciales CC El Encuentro, El Sitio San Miguel'),
	(1103, 'CHALATENANGO', 'EL PARAÍSO', 'Correos El Paraiso'),
	(1105, 'SANTA ANA', 'SANTA ANA', 'Centros Comerciales Metrocentro Santa Ana');



